---
output:
  pdf_document:
    includes:
      before_body: TP-title.tex
      in_header: preamble-latex.tex
---  
\centering  

\clearpage  

\tableofcontents   

\justify  
\clearpage  

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r paquetages, message=FALSE, eval=TRUE, include=FALSE, echo = FALSE}
### Liste des paquetages
liste.paquetage <- c("ggplot2", "CASdatasets")
### On installe les paquetages de la liste qu'on a pas déjà
inst <- liste.paquetage %in% installed.packages()
if(length(liste.paquetage[!inst]) > 0) install.packages(liste.paquetage[!inst])
lapply(liste.paquetage, require, character.only = TRUE)
```

# Introduction

Pour ce travail, l'objectif est de construire un modèle de prime pure pour la somme des réclamations (tous types confondus). 

\clearpage  

# Analyse Exploratoire

```{r donnees, include=FALSE, echo = FALSE}

data(brvehins1a)
Veh <- brvehins1a

Veh$ClaimNb <- Veh$ClaimNbRob + Veh$ClaimNbPartColl + Veh$ClaimNbTotColl + Veh$ClaimNbFire + Veh$ClaimNbOther
Veh$ClaimAmount <- Veh$ClaimAmountRob + Veh$ClaimAmountPartColl + Veh$ClaimAmountTotColl + Veh$ClaimAmountFire + Veh$ClaimAmountOther
VehClaimOnly <- Veh[Veh$ClaimAmount > 0, ]

```


```{r HistClaim, message=FALSE, echo = FALSE}

ggplot(VehClaimOnly, aes(x=ClaimAmount))+
  geom_histogram()

```

\clearpage 


# Conclusion
